### ISSUE TITLE
Changes needed to the swagger UI configuration to make it work as expected.

### ISSUE THREAD

**Issue by kalnikh** [nbbrd/jdemetra-ws#11]
Hello,

We have deployed Jdemetra+ Web service in our environment. 
We had to make some changes to the swagger UI configuration for it to work as expected.
 
1. Host Name is hard-coded in the Servlet configuring Swagger UI (SwaggerJaxrsConfig) as "localhost". This hard-coding needs to be removed.

2. Servlet configuring Swagger UI (SwaggerJaxrsConfig) is not picking up context-root dynamically. 
Some times the context-root is decided at the deployment time and thus it will be good if context-root can be picked up dynamically. (as below)
 beanConfig.setBasePath(servletConfig.getServletContext().getContextPath()+"/api");

3.  The main page(index.html) has JavaScript to pick-up the host-name from the URL  to load up the swagger.json which did not work as expected. JavaScript had to be adapted to pick-up the host as below:

      var base= document.URL;
      var url=base.substr(0,base.indexOf("/", base.indexOf("/", base.indexOf("//") + 2)));

Can you please include these changes in the next version of JDemetra+Web service. This way it will be easier to deploy and use the service from the downloaded sources. 

Thank you. 
Best Regards,
Nikhil Kale

**Comment by maggima** [comment]
Hello,
Thank you for your great suggestions. I already implemented those changes locally but I still need to test some things to see if everything is still working properly.
Regards,
Mats

**Comment by kalnikh** [comment]
Hello,

Thanks for the info.  
Do you have any idea when(roughly) next version of JDemetra+ Web service will be available?

Best Regards,
Nikhil

**Comment by maggima** [comment]
I've commited the changes you've suggested.

**Comment by kalnikh** [comment]
Thank you very much...
