### ISSUE TITLE
JSON Response instead of XML

### ISSUE THREAD

**Issue by srothmei** [nbbrd/jdemetra-ws#12]
I've recently upgrade to the latest version of the Webservice but somehow it seems the XML-Output isn't working properly anymore.
Before using the latest build, I used /x13/requests to perform X13-based Seasonal Adjustment. By incorporating the flag **content-type: application/xml** into my request-header, i was perfectly able to obtain the desired XML file.

Since i've upgrade the installation, i'm receiving a JSON file instead of an XML file. 
As stated above, the webservice call and the code itself remains the same as before, thus i think this might be a bug.

**Comment by maggima** [comment]
Have you tried adding the `Accept` header to the request with `application/xml` ?
It tells the service that you want to process an XML response.

**Comment by srothmei** [comment]
Okay that actually solved the problem, thank you.
I was just confused because previously i already used `content-type: application/xml` which delivered the desired XML output.
Anyway, adding `Accept: application/xml` did the job.

**Comment by maggima** [comment]
`Content-Type` is used to specify the type of the message body you're sending as a request.
