### ISSUE TITLE
Access-control-origin settings

### ISSUE THREAD

**Issue by kalnikh** [nbbrd/jdemetra-ws#9]
Hello, 

We have deployed the Demetra webapp on our local tomcat server. However, when I invoke the URL, I see "Can't read from server. It may not have the appropriate access-control-origin settings." Error.  Do you think this could be CORS issue? 

I can successfully run the standalone version of Jdemetra. Does this mean CORS configuration is not set up for the Webapp version? 

I can also see on the "Getting started" page that besides CORS, SSL security needs to be set up. Currently, we do not have SSL Security set up on server. Can you please also inform me if SSL is must for running Jdemetra webapp?

Thank you,
Nikhil Kale

**Comment by maggima** [comment]
Hello,
I've looked at your problem and it seems that it's a problem with how Tomcat handles configuration of servlets. It needs a web.xml file so the filters, servlets,... are fetched correctly. I got it working by adding that web.xml file in the WEB-INF directory.
It may be not perfect as I don't have a big experience with Tomcat so feel free to comment it.

```xml
<?xml version="1.0" encoding="UTF-8"?>

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd" version="3.1">
    <display-name>JDemetra Web Service</display-name>
    <servlet>
        <servlet-name>jersey-servlet</servlet-name>
        <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>ec.nbb.demetra.ApplicationConfig</param-value>
        </init-param>
        <init-param>
            <param-name>jersey.config.server.provider.packages</param-name>
            <param-value>io.swagger.jaxrs.listing,ec.nbb.demetra.rest</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    
    <servlet-mapping>
        <servlet-name>jersey-servlet</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>

    <filter>
        <filter-name>HTML5CorsFilter</filter-name>
        <filter-class>ec.nbb.ws.filters.HTML5CorsFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>HTML5CorsFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
    
    <servlet>
        <servlet-name>SwaggerJaxrsConfig</servlet-name>
        <servlet-class>ec.nbb.demetra.SwaggerJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>/demetra/api</param-value>
        </init-param>
        <init-param>
            <param-name>scan.all.resources</param-name>
            <param-value>true</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>
    
    <session-config>
        <session-timeout>30</session-timeout>
    </session-config>
</web-app>
```

I hope it resolves your problem.

Mats

**Comment by kalnikh** [comment]
Hello,

Thank you for looking in this issue.  When I used the web.xml provided by you and deployed the webapp, I came across issue of some classes not being found at deployment time. So, When I added the Jar files for these, I am now getting LinkageError as below:

 java.lang.LinkageError: loader constraint violation: when resolving method "org.glassfish.jersey.server.internal.ConfigHelper.getContainerLifecycleListener(Lorg/glassfish/jersey/server/ApplicationHandler;)Lorg/glassfish/jersey/server/spi/ContainerLifecycleListener;" the class loader (instance of org/apache/catalina/loader/ParallelWebappClassLoader) of the current class, org/glassfish/jersey/servlet/ServletContainer, and the class loader (instance of java/net/URLClassLoader) for the method's defining class, org/glassfish/jersey/server/internal/ConfigHelper, have different Class objects for the type org/glassfish/jersey/server/ApplicationHandler used in the signature

In the POM, I see that the Jersey version is set to 2.21, however, with this some classes are not found at the deployment time. 

Since you already have the working version, can you please inform me which versions of Jar files you are using for jersey server api and hk2 api. I will try to use the same artefacts during deployment to avoid any further linking problems. 

Thanks & Best Regards,
Nikhil

**Comment by maggima** [comment]
Hello,
Which version of Tomcat are you using ? (I tried on the 8.0.33).
I had that kind of problem with Glassfish 4 as it was shipped with older versions of the libraries so it was conflicting (take a look at the wiki in the Getting Started chapter)
You should find all versions I'm using in my code in the different POM files (parent, ws-commons, demetra-webapp).

Best Regards,

Mats

**Comment by kalnikh** [comment]
Hello,  
Thank you for information. So, It seems I will need to find out which libraries are causing such a conflict and replace them.  The version of Tomcat is 8.5.8.  
The main problem is that if I use libraries that are provided by default by the project POM then I do get following error at deployment time:
 java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.RuntimeExecutorsBinder$BackgroundSchedulerLiteral

Best Regards,
Nikhil

**Comment by kalnikh** [comment]
Hello,

Thanks for all your help.  I could get the web service working now. We could close this issue

Best Regards,
Nikhil
